name: Publish on NPM registry
on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM depedencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
  format:
    name: Check format with Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM dependencies
        run: npm install
      - name: Run Prettier
        run: npm run format:check
  test:
    name: Test with Jest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM depedencies
        run: npm install
      - name: Run Jest
        run: npm run test
  publish:
    name: Publish to GitHub registry
    needs: [lint, format, test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    env:
      HUSKY: '0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ensure tag validity
        run: |
          if [ $(jq -r .version package.json) != ${GITHUB_REF/refs\/tags\//} ]; then
            echo "Error: $GITHUB_REF does not match package.json version"
            exit 1
          fi
      - name: Install NPM dependencies
        run: npm install
      - name: Publish new release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          access: public
